### ISSUE TITLE
Improved caching / releasing

### ISSUE THREAD

**Issue by aslakhellesoy** [kevinswiber/request-caching#1]
Hi @kevinswiber 

I have made some improvements in my fork. Would you be interested in merging them into yours? Alternatively, would you be interested in giving me npm karma to publish updated packages from my fork?

Cheers,
Aslak

**Comment by kevinswiber** [comment]
Yeah, I'd be happy to take a look!

After doing some initial work on this, my focus shifted elsewhere.  I recently built an HTTP caching module for [Argo](https://github.com/argo/argo), an API proxy/origin server I'm working on.  There might be something I can pull from that, too, though the perspective is from a proxy close to the server so the rules differ slightly.

Also, no problem adding you as a maintainer on NPM.  I'm happy someone else cares about this.  I think it's pretty important.  :+1: 

Thanks!

**Comment by aslakhellesoy** [comment]
Sounds great! Let's see what @missinglink is up to as well - he just posted several issues to my fork. Maybe he'll be interested in maintaining this as well.

**Comment by missinglink** [comment]
Sure, I can help out. Is there any interest from @mikeal and the `request` team to merge this with `request` or will it remain a stand-alone module?

**Comment by mikeal** [comment]
is there an advantage to merging it in to `request`? adding it as an option to request looks clunkier than just requiring it and getting an identical API :)

**Comment by kevinswiber** [comment]
I think my preference might be to keep it separate, though @mikeal's
blessing would be helpful for awareness.  I'd also like to see a caching
interface defined with storage strategies split up into separate modules
(the InMemoryCache can stay so it works out of the box).

In addition... I've built an all-JS persistent key-value store (
https://github.com/argo/medea) that I'm using for caching storage in a
reverse proxy.  I'd like to apply that to the client side, as well.

On Mon, Jul 1, 2013 at 1:55 PM, Peter Johnson notifications@github.comwrote:

> Sure, I can help out. Is there any interest from @mikealhttps://github.com/mikealand the
> request team to merge this with request or will it remain a stand-alone
> module?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kevinswiber/request-caching/issues/1#issuecomment-20298605
> .

## 

Kevin Swiber
Projects: https://github.com/kevinswiber
Twitter: @kevinswiber

**Comment by kevinswiber** [comment]
@mikeal Agreed.  And I haven't seen too many people clamoring for this feature on the request issues list.  Keeping it separate also allows us to iterate faster without impacting the highly-depended-on request's version policy.

**Comment by aslakhellesoy** [comment]
Having thought about it I agree it would be easier to maintain if kept separate. I agree that some more awareness around this would improve the quality of the lib, so if @mikeal could link here from the `request` README that would probably help.

**Comment by kevinswiber** [comment]
@aslakhellesoy I added you as a collaborator to the Git repo and made you an owner of the NPM package.  Let me know if that suffices.  I'd love to talk about production-readiness in a separate thread.

Let me know if that's cool, and I'll close the issue.

Thanks!

**Comment by aslakhellesoy** [comment]
@kevinswiber thanks a lot that works great.

**Comment by aslakhellesoy** [comment]
@kevinswiber I don't have karma to push to your repo. Can you check again please?

**Comment by kevinswiber** [comment]
Sorry about that. Try again.

Sent from my iPhone

On Jul 11, 2013, at 4:39 PM, "Aslak Hellesøy" notifications@github.com
wrote:

@kevinswiber https://github.com/kevinswiber I don't have karma to push to
your repo. Can you check again please?

—
Reply to this email directly or view it on
GitHubhttps://github.com/kevinswiber/request-caching/issues/1#issuecomment-20840522
.
